{
	"version": 1740745378,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/trumpbimp-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/backgroundnew-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/tile-sheet2.png",
		"images/tile-sheet3.png",
		"images/tile-sheet4.png",
		"images/tile-sheet5.png",
		"images/tile-sheet6.png",
		"images/tile-sheet7.png",
		"images/tile-sheet8.png",
		"images/europe-sheet0.png",
		"images/asia2-sheet0.png",
		"images/pickonesheet-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/trump 2 (1).m4a",
		"media/trump 2 (1).ogg",
		"media/drop.m4a",
		"media/drop.ogg",
		"media/us aid - bgm.m4a",
		"media/us aid - bgm.ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}